/*
 * TO CHANGE PRODUCT NAME, DESCRIPTION, IMAGE, CATEGORY, BADGE OR WHY WE PICKED IT,
 * edit the matching object below. Keep values as plain text.
 * TO CHANGE AMAZON LINK: replace AMAZON_LINK_01 ... AMAZON_LINK_10 with your
 * Amazon Associates-generated URLs. Unchanged placeholders are safely disabled.
 * TO CHANGE PRODUCT IMAGE: use a local file under images/products/ and update image.
 */
const products = [
  { id: 1, name: "Large-Print World History Book", category: "reading-history", description: "An accessible history book designed for comfortable reading and leisurely exploration of the past.", whyWePickedIt: "A natural fit for anyone who enjoys the historical stories featured on The Last Storyteller.", image: "images/products/reading-history.webp", imageAlt: "An unmarked history book and puzzle book on a wooden reading table", amazonUrl: "https://amzn.to/4rJBu7P", badge: "History Pick", featured: false },
  { id: 2, name: "Large-Print Word Search & Puzzle Book", category: "reading-history", description: "A relaxing collection of word searches and puzzles designed for easy, comfortable reading.", whyWePickedIt: "A simple way to unwind while keeping the mind active.", image: "images/products/reading-history.webp", imageAlt: "A puzzle book and reading glasses beside an unmarked book", amazonUrl: "https://amzn.to/3U5VEwj", badge: "Reader Pick", featured: false },
  { id: 3, name: "Hands-Free Floor Magnifier with LED Light", category: "reading-history", description: "A floor-standing magnifier with an adjustable stand and rechargeable light for reading, sewing and detailed craft work.", whyWePickedIt: "The adjustable stand keeps both hands free for close work, while the built-in light can help with reading, sewing and crafts.", image: "https://m.media-amazon.com/images/I/71Z8rdSvu9L._AC_SL1500_.jpg", imageAlt: "Floor-standing magnifying glass with an illuminated lens and adjustable stand", amazonUrl: "https://amzn.to/4AKwKTt", badge: "Useful Find", featured: true },
  { id: 4, name: "Supportive Reading & Back Cushion", category: "home-comfort", description: "A comfortable support cushion for reading, relaxing or spending longer periods sitting.", whyWePickedIt: "Comfort matters when you're settling in with a good book, documentary or long story.", image: "images/products/home-comfort.webp", imageAlt: "Layered cushions and a soft throw on a reading chair", amazonUrl: "AMAZON_LINK_04", badge: "Comfort Pick", featured: false },
  { id: 5, name: "Soft Lightweight Throw Blanket", category: "home-comfort", description: "A versatile lightweight blanket for the sofa, reading chair or bedroom.", whyWePickedIt: "A straightforward comfort item that works well for quiet evenings at home.", image: "images/products/home-comfort.webp", imageAlt: "A muted green throw draped over a comfortable chair", amazonUrl: "AMAZON_LINK_05", badge: "Home Pick", featured: false },
  { id: 6, name: "Easy-to-Read Digital Clock", category: "home-comfort", description: "A simple clock with a large, clear display designed to be readable from across a room.", whyWePickedIt: "Practical products do not need to be complicated to be useful.", image: "images/products/home-comfort.webp", imageAlt: "A large-display digital clock beside a reading chair", amazonUrl: "AMAZON_LINK_06", badge: "Practical Pick", featured: false },
  { id: 7, name: "Padded Garden Kneeler & Seat with Tool Pouches", category: "garden-outdoors", description: "A foldable garden kneeler with a wide padded cushion that converts into a low seat, plus pouches for keeping tools close at hand.", whyWePickedIt: "The padded surface offers support while gardening, and the side pouches keep small tools within reach.", image: "https://m.media-amazon.com/images/I/81Zqdu8EA3L._AC_SL1280_.jpg", imageAlt: "Foldable padded garden kneeler seat with side tool pouches", amazonUrl: "https://amzn.to/4y0kpIa", badge: "Garden Pick", featured: true },
  { id: 8, name: "Rechargeable Emergency Lantern", category: "garden-outdoors", description: "A portable rechargeable light useful for the garden, power outages, camping and emergencies.", whyWePickedIt: "One of those practical items that can become especially valuable when the unexpected happens.", image: "images/products/garden-outdoors.webp", imageAlt: "Gardening tools set out in a leafy outdoor space", amazonUrl: "AMAZON_LINK_08", badge: "Preparedness Pick", featured: false },
  { id: 9, name: "Adjustable Book & Tablet Stand with Storage", category: "everyday-finds", description: "A wooden stand with built-in storage that holds books and tablets at an adjustable angle.", whyWePickedIt: "Useful for hands-free reading, cooking and following instructions, with storage to keep small essentials close by.", image: "https://m.media-amazon.com/images/I/81ai9UHBhJL._AC_SL1500_.jpg", imageAlt: "Adjustable wooden book and tablet stand with storage", amazonUrl: "https://amzn.to/4hFD99M", badge: "Everyday Pick", featured: true },
  { id: 10, name: "Insulated Travel Mug", category: "everyday-finds", description: "A reusable insulated mug designed to keep drinks warmer or cooler while at home or on the move.", whyWePickedIt: "Simple, practical and useful enough to become part of an everyday routine.", image: "images/products/everyday-finds.webp", imageAlt: "A plain insulated travel mug beside a book stand", amazonUrl: "AMAZON_LINK_10", badge: "Daily Pick", featured: false }
];
